// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/storage/models/attendance_session_ob.dart';
import 'core/storage/models/subject_ob.dart';
import 'core/storage/models/sync_queue_item_ob.dart';
import 'core/storage/models/task_ob.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1571069325127350334),
    name: 'AttendanceSessionOB',
    lastPropertyId: const obx_int.IdUid(8, 5954290968150253702),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8612429548014660718),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7465390459362549893),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 1026113053704653456),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 379187953861923399),
        name: 'subjectId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6830057244750121034),
        name: 'sessionDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2504872023707202859),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4657519528406444578),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1466296767918860579),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5954290968150253702),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2173586807081284289),
    name: 'SubjectOB',
    lastPropertyId: const obx_int.IdUid(8, 7936124218063268579),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2131183376924049827),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7926640819361611286),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 93273800449625603),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3662903385910596523),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3259322505862841117),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2018702436030033686),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6113979673155018488),
        name: 'thresholdPct',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5420479767986780783),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7936124218063268579),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3923350661976624865),
    name: 'SyncQueueItemOB',
    lastPropertyId: const obx_int.IdUid(8, 1957926309934346403),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2147900231898069444),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8489880528599310614),
        name: 'operationType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5475483240925053361),
        name: 'entityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7731367604650262764),
        name: 'entityId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6768785195024704007),
        name: 'payloadJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4954017117214230983),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3960636396170822235),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1957926309934346403),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 747617318096413486),
    name: 'TaskOB',
    lastPropertyId: const obx_int.IdUid(13, 4173909836098834722),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7831323630261825314),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2328218892484000219),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 6888479911234210361),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7017561117936893862),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6676433182399214768),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4309495533117718738),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3676596111674487193),
        name: 'dueDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6905768699954362174),
        name: 'priority',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6858283564469232672),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 412860182426133977),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8225314888831368701),
        name: 'completedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6289159195257553487),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 368302150862451734),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4173909836098834722),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 747617318096413486),
    lastIndexId: const obx_int.IdUid(3, 6888479911234210361),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AttendanceSessionOB: obx_int.EntityDefinition<AttendanceSessionOB>(
      model: _entities[0],
      toOneRelations: (AttendanceSessionOB object) => [],
      toManyRelations: (AttendanceSessionOB object) => {},
      getId: (AttendanceSessionOB object) => object.obId,
      setId: (AttendanceSessionOB object, int id) {
        object.obId = id;
      },
      objectToFB: (AttendanceSessionOB object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final subjectIdOffset = fbb.writeString(object.subjectId);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(9);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, subjectIdOffset);
        fbb.addInt64(3, object.sessionDate.millisecondsSinceEpoch);
        fbb.addOffset(4, statusOffset);
        fbb.addBool(5, object.isSynced);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final subjectIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sessionDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = AttendanceSessionOB(
          obId: obIdParam,
          id: idParam,
          subjectId: subjectIdParam,
          sessionDate: sessionDateParam,
          status: statusParam,
          isSynced: isSyncedParam,
          updatedAt: updatedAtParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    SubjectOB: obx_int.EntityDefinition<SubjectOB>(
      model: _entities[1],
      toOneRelations: (SubjectOB object) => [],
      toManyRelations: (SubjectOB object) => {},
      getId: (SubjectOB object) => object.obId,
      setId: (SubjectOB object, int id) {
        object.obId = id;
      },
      objectToFB: (SubjectOB object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final userIdOffset = fbb.writeString(object.userId);
        final nameOffset = fbb.writeString(object.name);
        final codeOffset = object.code == null
            ? null
            : fbb.writeString(object.code!);
        fbb.startTable(9);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, codeOffset);
        fbb.addInt64(5, object.thresholdPct);
        fbb.addBool(6, object.isSynced);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final thresholdPctParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = SubjectOB(
          obId: obIdParam,
          id: idParam,
          userId: userIdParam,
          name: nameParam,
          code: codeParam,
          thresholdPct: thresholdPctParam,
          isSynced: isSyncedParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    SyncQueueItemOB: obx_int.EntityDefinition<SyncQueueItemOB>(
      model: _entities[2],
      toOneRelations: (SyncQueueItemOB object) => [],
      toManyRelations: (SyncQueueItemOB object) => {},
      getId: (SyncQueueItemOB object) => object.obId,
      setId: (SyncQueueItemOB object, int id) {
        object.obId = id;
      },
      objectToFB: (SyncQueueItemOB object, fb.Builder fbb) {
        final operationTypeOffset = fbb.writeString(object.operationType);
        final entityTypeOffset = fbb.writeString(object.entityType);
        final entityIdOffset = fbb.writeString(object.entityId);
        final payloadJsonOffset = fbb.writeString(object.payloadJson);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(9);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, operationTypeOffset);
        fbb.addOffset(2, entityTypeOffset);
        fbb.addOffset(3, entityIdOffset);
        fbb.addOffset(4, payloadJsonOffset);
        fbb.addInt64(5, object.retryCount);
        fbb.addOffset(6, statusOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final operationTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final entityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final entityIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final payloadJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final retryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = SyncQueueItemOB(
          obId: obIdParam,
          operationType: operationTypeParam,
          entityType: entityTypeParam,
          entityId: entityIdParam,
          payloadJson: payloadJsonParam,
          retryCount: retryCountParam,
          status: statusParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    TaskOB: obx_int.EntityDefinition<TaskOB>(
      model: _entities[3],
      toOneRelations: (TaskOB object) => [],
      toManyRelations: (TaskOB object) => {},
      getId: (TaskOB object) => object.obId,
      setId: (TaskOB object, int id) {
        object.obId = id;
      },
      objectToFB: (TaskOB object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final userIdOffset = fbb.writeString(object.userId);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final priorityOffset = fbb.writeString(object.priority);
        final statusOffset = fbb.writeString(object.status);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(14);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addInt64(5, object.dueDate?.millisecondsSinceEpoch);
        fbb.addOffset(6, priorityOffset);
        fbb.addOffset(7, statusOffset);
        fbb.addOffset(8, tagsOffset);
        fbb.addInt64(9, object.completedAt?.millisecondsSinceEpoch);
        fbb.addBool(10, object.isSynced);
        fbb.addInt64(11, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(12, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final completedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final dueDateParam = dueDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueDateValue);
        final priorityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 20, []);
        final completedAtParam = completedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(completedAtValue);
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
        );
        final object = TaskOB(
          obId: obIdParam,
          id: idParam,
          userId: userIdParam,
          title: titleParam,
          description: descriptionParam,
          dueDate: dueDateParam,
          priority: priorityParam,
          status: statusParam,
          tags: tagsParam,
          completedAt: completedAtParam,
          isSynced: isSyncedParam,
          updatedAt: updatedAtParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AttendanceSessionOB] entity fields to define ObjectBox queries.
class AttendanceSessionOB_ {
  /// See [AttendanceSessionOB.obId].
  static final obId = obx.QueryIntegerProperty<AttendanceSessionOB>(
    _entities[0].properties[0],
  );

  /// See [AttendanceSessionOB.id].
  static final id = obx.QueryStringProperty<AttendanceSessionOB>(
    _entities[0].properties[1],
  );

  /// See [AttendanceSessionOB.subjectId].
  static final subjectId = obx.QueryStringProperty<AttendanceSessionOB>(
    _entities[0].properties[2],
  );

  /// See [AttendanceSessionOB.sessionDate].
  static final sessionDate = obx.QueryDateProperty<AttendanceSessionOB>(
    _entities[0].properties[3],
  );

  /// See [AttendanceSessionOB.status].
  static final status = obx.QueryStringProperty<AttendanceSessionOB>(
    _entities[0].properties[4],
  );

  /// See [AttendanceSessionOB.isSynced].
  static final isSynced = obx.QueryBooleanProperty<AttendanceSessionOB>(
    _entities[0].properties[5],
  );

  /// See [AttendanceSessionOB.updatedAt].
  static final updatedAt = obx.QueryDateProperty<AttendanceSessionOB>(
    _entities[0].properties[6],
  );

  /// See [AttendanceSessionOB.createdAt].
  static final createdAt = obx.QueryDateProperty<AttendanceSessionOB>(
    _entities[0].properties[7],
  );
}

/// [SubjectOB] entity fields to define ObjectBox queries.
class SubjectOB_ {
  /// See [SubjectOB.obId].
  static final obId = obx.QueryIntegerProperty<SubjectOB>(
    _entities[1].properties[0],
  );

  /// See [SubjectOB.id].
  static final id = obx.QueryStringProperty<SubjectOB>(
    _entities[1].properties[1],
  );

  /// See [SubjectOB.userId].
  static final userId = obx.QueryStringProperty<SubjectOB>(
    _entities[1].properties[2],
  );

  /// See [SubjectOB.name].
  static final name = obx.QueryStringProperty<SubjectOB>(
    _entities[1].properties[3],
  );

  /// See [SubjectOB.code].
  static final code = obx.QueryStringProperty<SubjectOB>(
    _entities[1].properties[4],
  );

  /// See [SubjectOB.thresholdPct].
  static final thresholdPct = obx.QueryIntegerProperty<SubjectOB>(
    _entities[1].properties[5],
  );

  /// See [SubjectOB.isSynced].
  static final isSynced = obx.QueryBooleanProperty<SubjectOB>(
    _entities[1].properties[6],
  );

  /// See [SubjectOB.updatedAt].
  static final updatedAt = obx.QueryDateProperty<SubjectOB>(
    _entities[1].properties[7],
  );
}

/// [SyncQueueItemOB] entity fields to define ObjectBox queries.
class SyncQueueItemOB_ {
  /// See [SyncQueueItemOB.obId].
  static final obId = obx.QueryIntegerProperty<SyncQueueItemOB>(
    _entities[2].properties[0],
  );

  /// See [SyncQueueItemOB.operationType].
  static final operationType = obx.QueryStringProperty<SyncQueueItemOB>(
    _entities[2].properties[1],
  );

  /// See [SyncQueueItemOB.entityType].
  static final entityType = obx.QueryStringProperty<SyncQueueItemOB>(
    _entities[2].properties[2],
  );

  /// See [SyncQueueItemOB.entityId].
  static final entityId = obx.QueryStringProperty<SyncQueueItemOB>(
    _entities[2].properties[3],
  );

  /// See [SyncQueueItemOB.payloadJson].
  static final payloadJson = obx.QueryStringProperty<SyncQueueItemOB>(
    _entities[2].properties[4],
  );

  /// See [SyncQueueItemOB.retryCount].
  static final retryCount = obx.QueryIntegerProperty<SyncQueueItemOB>(
    _entities[2].properties[5],
  );

  /// See [SyncQueueItemOB.status].
  static final status = obx.QueryStringProperty<SyncQueueItemOB>(
    _entities[2].properties[6],
  );

  /// See [SyncQueueItemOB.createdAt].
  static final createdAt = obx.QueryDateProperty<SyncQueueItemOB>(
    _entities[2].properties[7],
  );
}

/// [TaskOB] entity fields to define ObjectBox queries.
class TaskOB_ {
  /// See [TaskOB.obId].
  static final obId = obx.QueryIntegerProperty<TaskOB>(
    _entities[3].properties[0],
  );

  /// See [TaskOB.id].
  static final id = obx.QueryStringProperty<TaskOB>(_entities[3].properties[1]);

  /// See [TaskOB.userId].
  static final userId = obx.QueryStringProperty<TaskOB>(
    _entities[3].properties[2],
  );

  /// See [TaskOB.title].
  static final title = obx.QueryStringProperty<TaskOB>(
    _entities[3].properties[3],
  );

  /// See [TaskOB.description].
  static final description = obx.QueryStringProperty<TaskOB>(
    _entities[3].properties[4],
  );

  /// See [TaskOB.dueDate].
  static final dueDate = obx.QueryDateProperty<TaskOB>(
    _entities[3].properties[5],
  );

  /// See [TaskOB.priority].
  static final priority = obx.QueryStringProperty<TaskOB>(
    _entities[3].properties[6],
  );

  /// See [TaskOB.status].
  static final status = obx.QueryStringProperty<TaskOB>(
    _entities[3].properties[7],
  );

  /// See [TaskOB.tags].
  static final tags = obx.QueryStringVectorProperty<TaskOB>(
    _entities[3].properties[8],
  );

  /// See [TaskOB.completedAt].
  static final completedAt = obx.QueryDateProperty<TaskOB>(
    _entities[3].properties[9],
  );

  /// See [TaskOB.isSynced].
  static final isSynced = obx.QueryBooleanProperty<TaskOB>(
    _entities[3].properties[10],
  );

  /// See [TaskOB.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TaskOB>(
    _entities[3].properties[11],
  );

  /// See [TaskOB.createdAt].
  static final createdAt = obx.QueryDateProperty<TaskOB>(
    _entities[3].properties[12],
  );
}
